project:
  type: website
  output-dir: docs
website:
  title: "Abuja R User Group"
  site-url: https://abujarug.github.io/
  description: "Abuja R User Group website"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - text: Feedback
        href: feedback.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/abuja-r-user-group-669ab521b/
      - icon: github
        href: https://github.com/abujarug
      - icon: twitter
        href: https://twitter.com/AbujaRUG
      - icon: youtube
        href: https://www.youtube.com/@abujarusergroup
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

